### ISSUE TITLE
Error: Model 'gpt-4' is unavailable in openai.ts

### ISSUE THREAD

**Issue by simasrazi** [eumemic/ai-legion#20]
I encountered an error while trying to use the GPT-4 model (GPT-3.5-turbo works fine) within the project. The error message is as follows:

```
Agent 1 encountered the following problem while attempting to take action:
Error: Model 'gpt-4' is unavailable.
    at task (C:\Microsoft\legion\src\openai.ts:35:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Microsoft\legion\src\make-decision.ts:22:29
```

Please investigate this issue and provide guidance on how to resolve it. Thank you!

**Comment by eumemic** [comment]
This means you don’t have GPT-4 access. Did you sign up for the waitlist, and then get notified of approval?

**Comment by simasrazi** [comment]
Thank you, that was indeed the issue here.

https://openai.com/waitlist/gpt-4-api
