### ISSUE TITLE
Agent stuck in a loop

### ISSUE THREAD

**Issue by srijansaxena11** [eumemic/ai-legion#4]
The agent is stuck in a loop.
```
=============

Agent 1 -> System:

writeNote
title: Resources for Ruby on Rails Learning
content:
% ff9d7713-0bb0-40d4-823c-5a66de48761b%
- Ruby on Rails Guides: https://guides.rubyonrails.org/
- Ruby on Rails API: https://api.rubyonrails.org/
- Intermediate Rails: Understanding Models, Views and Controllers: https://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/
% ff9d7713-0bb0-40d4-823c-5a66de48761b%

viewNote
title: Resources for Ruby on Rails Learning

=============

System -> Agent 1:

--- ERROR ---

Your action could not be parsed. Did you fail to wrap the entirety of a multi-line parameter value with the multi-line delimiter (`% ff9d7713-0bb0-40d4-823c-5a66de48761b`)?

=============
```

**Comment by eumemic** [comment]
The `gpt-3.5-Turbo` agent sometimes gets stuck in error loops like this because it’s just too dumb to learn from its mistakes. Is that what you’re using?

**Comment by srijansaxena11** [comment]
> The `gpt-3.5-turbo` agent sometimes gets stuck in error loops like this because it’s just too dumb to learn from its mistakes. Is that what you’re using?

Yes I am using the default gpt-3.5-turbo model. Thanks for clarifying. I asked it to remove the ":" from the content part. It took multiple attempts but I think it got out of it. Thanks for clarifying.

**Comment by srijansaxena11** [comment]
It is getting stuck in every step now:

![image](https://user-images.githubusercontent.com/34964694/231294144-123822db-6e5b-4d45-a46a-8fe814713bbc.png)
