### ISSUE TITLE
Endless stream of error logs with 401

### ISSUE THREAD

**Issue by Jaikant** [eumemic/ai-legion#7]
This is a very nice project. I liked the idea and tried to test it out but there was an endless stream of res objects with 401 error code when a did a "\help" on the console $. 
Probably there are many API calls getting rejected by openAI. For a while it was scary if the API gets called endlessly on the back it could get expensive, so I left it there. 

It would be nice, if you could explain in more detail some use cases for this project.

**Comment by eumemic** [comment]
There's no user-facing commands available on the console, whatever you type will just be broadcast as a message to all agents. I'm not sure what the 401 error is about, could you provide a more detailed error transcript?
