### ISSUE TITLE
Stuck in a multi-line delimiter error loop.

### ISSUE THREAD

**Issue by obsidianbtc** [eumemic/ai-legion#9]
Agent 1 -> System:

writeNote
title: Trending NFT Collections at TradePort.xyz
content: % ff9d7713-0bb0-40d4-823c-5a66de48761b
The website summary does not provide detailed information on the respective volumes of the trending NFT collections. It would be necessary to visit the site and retrieve the information manually.
% ff9d7713-0bb0-40d4-823c-5a66de48761b

sendMessage
recipient: Control
message: % ff9d7713-0bb0-40d4-823c-5a66de48761b
I could not find the detailed information on the respective volumes of the trending NFT collections directly from [TradePort.xyz](https://www.tradeport.xyz). To obtain the requested data, it would be necessary to visit the site and retrieve the information manually.
% ff9d7713-0bb0-40d4-823c-5a66de48761b

=============

System -> Agent 1:

--- ERROR ---

Your action could not be parsed. Did you fail to wrap the entirety of a multi-line parameter value with the multi-line delimiter (`% ff9d7713-0bb0-40d4-823c-5a66de48761b`)?

**Comment by HenkDz** [comment]
Having this same error in addition to this one:
`content: Error extracting content from https://www.amazon.com/Best-Sellers-Mens-Shoes/: Failed to launch the browser process!

TROUBLESHOOTING: https://pptr.dev/troubleshooting

I am unable to extract content from the provided URL.`

**Comment by eumemic** [comment]
Re. the first error, agents just need to figure out how to use the delimiter correctly through trial and error (they're instructed how to do it in the primer prompt). Sometimes GPT-3.5 agents get stuck in an error loop and never figure it out, GPT-4 agents are much better.

Re. the second issue, I've heard other people report this problem, are you using a windows system? My only idea so far is to try running inside a docker image with a nodejs base image. The issue has to do with running chromium (via puppeteer) for dynamic web scraping. I had an earlier version of the `readPage` action which used a much simpler mechanism but was limited to static content; I might have it fall back to this when the more sophisticated solution fails.

**Comment by eumemic** [comment]
Someone shared this in the discord, maybe it applies to your case? 
![8159CF11-3069-4A23-BFBA-8EA37E8B4481](https://user-images.githubusercontent.com/94939491/231595434-448e6284-6c3f-4947-b538-c0168f605d75.png)
